apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: aw-arch-demo
spec:
  environments:
    - name: dev
      build:
        from: feature/async-worker-architecture
  components:
    - name: api
      src: api
      ports:
        - name: http
          port: 8000
      publicPort: http
      secrets:
        - BROKER_URL
    - name: worker-a
      src: worker_a
      secrets:
        - BROKER_URL
      horizontalScaling:
        minReplicas: 0
        maxReplicas: 10
        triggers:
          - name: queue-length
            azureServiceBus:
              queueName: jobs.worker_a
              messageCount: 5
              activationMessageCount: 1
              connectionFromEnv: BROKER_URL
    - name: worker-b
      src: worker_b
      secrets:
        - BROKER_URL
      horizontalScaling:
        minReplicas: 0
        maxReplicas: 10
        triggers:
          - name: queue-length
            azureServiceBus:
              queueName: jobs.worker_b
              messageCount: 2
              activationMessageCount: 1
              connectionFromEnv: BROKER_URL
