apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-a
  template:
    metadata:
      labels:
        app: worker-a
    spec:
      containers:
        - name: worker-a
          image: aw-arch-demo-worker-a:latest
          imagePullPolicy: Never
          env:
            - name: REDIS_URL
              value: redis://redis:6379
