FROM python:3.12-slim

WORKDIR /app
COPY api/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY api/ .
COPY messaging /app/messaging
RUN pip install --no-cache-dir /app/messaging

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
